Repository CS2103JAN2018-F12-B4/main, pull requests merged in 2018-03, with the labels that each got.

#5 Enhancement - Find Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement

#39 Documentation v1.0
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/images/ruiqi.jpg
  docs/team/ZhangRuiqi.adoc
Labels: documentation

#43 Documentation: v1.0 (Part 1)
  docs/DeveloperGuide.adoc
Labels: documentation

#46 Update README.adoc
  README.adoc
Labels: documentation

#45 Enhancement: Edit prefixes for Add / Edit command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement

#50 Docs
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/melvin.jpg
Labels: documentation

#42 Enhancement: FindCommand
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement, priority.high

#61 Bug Fix: [AboutUs.adoc] Remove entry for "John Doe".
  docs/AboutUs.adoc
Labels: bug

#64 Enhancement: Add tag colours
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: enhancement, status.ongoing

#68 Add implementation details of FindCommand enhancements
  docs/DeveloperGuide.adoc
Labels: documentation

#67 Invalid commands yield red result text.
  src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: enhancement

#69 Add implementation details for LocateCommand in Developer Guide
  docs/DeveloperGuide.adoc
Labels: documentation

#71 [DeveloperGuide.adoc] Add implementation details for Tag Colours
  docs/DeveloperGuide.adoc
Labels: documentation

#72 Follow the standard and upload the image for documentation
  docs/DeveloperGuide.adoc
  docs/images/interface_of_locate.png
Labels: documentation

#58 Create Customer class and Runner class, both of which extends Person …
  build.gradle
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/customer/Customer.java
  src/main/java/seedu/address/model/person/customer/LateInterest.java
  src/main/java/seedu/address/model/person/customer/MoneyBorrowed.java
  src/main/java/seedu/address/model/person/customer/StandardInterest.java
  src/main/java/seedu/address/model/person/runner/Runner.java
  src/test/java/seedu/address/model/person/CustomerTest.java
Labels: priority.high, status.ongoing

#80 Date parser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.task

#78 Enhance ADD command to accept optional parameters and construct a Per…
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: type.enhancement

#81 Update User Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation, priority.high

#85 Delete Faulty and Redundant Test - CustomerTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
Labels: type.bug

#79 Add menu items and keyboard shortcuts
  src/main/java/seedu/address/commons/events/ui/ExecuteCommandRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PopulatePrefixesRequestEvent.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.high, type.epic

#87 Update user guide: layout and content
  docs/UserGuide.adoc
Labels: documentation

#84 Person page
  PersonPage.html
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/storage/HtmlWriter.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/storage/HtmlWriterTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: documentation, type.enhancement

#88 [DeveloperGuide.adoc] Update developer guide
  docs/DeveloperGuide.adoc
Labels: documentation

#95 update add command descriptions in UserGuide
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: documentation, priority.high
