Repository CS2103JAN2018-F12-B4/main, pull requests merged in 2018-04, with the labels that each got.

#100 Rework underlying implementation for keyboard shortcuts
  src/main/java/seedu/address/commons/events/ui/ExecuteCommandRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PopulatePrefixesRequestEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ImmediatelyExecutableCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
  src/main/java/seedu/address/logic/commands/PopulatableCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.low, type.enhancement

#102 Change keyboard shortcuts: "Alt" based to "Ctrl" based
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.medium, type.bug

#107 Update add command keyboard shortcut
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium, type.bug

#74 Locate a customer by name, email, phone, address and tags.
  docs/DeveloperGuide.adoc
  docs/images/locate_same_specifier.png
  src/main/java/seedu/address/commons/events/ui/LocateRequestEvent.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
  src/main/java/seedu/address/logic/parser/LocateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LocateCommandTest.java
Labels: priority.medium, status.ongoing, type.bug, type.epic

#76 Basic UI improvement
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/loanshark_logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.medium, type.enhancement, type.ui

#113 Assign command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/customer/Customer.java
  src/main/java/seedu/address/model/person/customer/LateInterest.java
  src/main/java/seedu/address/model/person/customer/MoneyBorrowed.java
  src/main/java/seedu/address/model/person/customer/StandardInterest.java
  src/main/java/seedu/address/model/person/runner/Runner.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, type.enhancement

#119 Add command update2
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/customer/Customer.java
Labels: priority.high

#118 Docs v1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.high, type.task

#120 Sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.medium, type.task

#121 update Add Command messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.medium, type.task

#122 Update user guide
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/Ui_old.png
Labels: documentation

#124 Add collate annotations [v1.4]
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ExecuteCommandRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PopulatePrefixesRequestEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ImmediatelyExecutableCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
  src/main/java/seedu/address/logic/commands/PopulatableCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: documentation, priority.high

#126 Minor changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: documentation, priority.medium, type.task

#132 Fix bug where a runner1 who was previous assigned customer1 would sti…
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/customer/Customer.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: type.bug

#136 Delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.high

#142 Various ui updates
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/customer/Customer.java
  src/main/java/seedu/address/model/person/runner/Runner.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.task, type.ui

#146 Home command
  src/main/java/seedu/address/commons/events/ui/HomeRequestEvent.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.enhancement

#149 Minor UI tweaks and documentation updates
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/test/java/guitests/GuiRobot.java
Labels: documentation, priority.medium, type.enhancement

#151 Update default database state
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.medium, type.enhancement

#152 Rebrand: LoanShark Manager -> HuatAh!
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: documentation, priority.medium, type.task

#155 Various bug fixes
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/customer/MoneyBorrowed.java
  src/main/java/seedu/address/model/person/customer/StandardInterest.java
Labels: type.bug

#157 Template and aliases tweaks
  README.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ExecuteCommandRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/HomeRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PopulatePrefixesRequestEvent.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: documentation, priority.low, type.enhancement

#159 Improve Locate Command messages
  src/main/java/seedu/address/logic/commands/LocateCommand.java
Labels: type.bug

#161 Edit command2
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/FieldsChangedEvent.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement

#163 [UserGuide.adoc] Update LocateCommand entry.
  docs/UserGuide.adoc
Labels: documentation, priority.medium

#164 Small updates to Messages, UG and DG
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Email.java
Labels: documentation, priority.medium, type.task

#167 Update Project Portfolio Page
  docs/team/melvintzw.adoc
Labels: documentation

#172 Update: Documentation
  docs/UserGuide.adoc
  docs/team/Der-Erlkonig.adoc
  docs/team/ZhangRuiqi.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/LocateCommand.java
Labels: documentation, priority.medium

#174 Doc v1.5
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation

#175 JUnit Tests: Parser and Commands
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/customer/LateInterest.java
  src/main/java/seedu/address/model/person/customer/MoneyBorrowed.java
  src/main/java/seedu/address/model/person/customer/StandardInterest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.high, type.task

#177 Tests parser and commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, type.task

#183 CommandBox enhancements
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.enhancement

#185 hardcoded setStyle() in PersonCard to detemine personCard colour base…
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.medium, type.enhancement

#193 More JUnit Tests
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/parser/LocateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/customer/LateInterestTest.java
  src/test/java/seedu/address/model/person/customer/MoneyBorrowedTest.java
  src/test/java/seedu/address/model/person/customer/StandardInterestTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: type.task

#195 Update documentation
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UI-start.PNG
  docs/images/Ui_old.png
Labels: documentation

#197 Doc v1.5
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/FindCommandSequenceDiagram.pptx
  docs/diagrams/Model2ComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagram_original.png
  docs/images/PersonListPanel.PNG
  docs/team/melvintzw.adoc
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: priority.high

#200 Update: Documentation
  docs/UserGuide.adoc
  docs/team/jonleeyz.adoc
Labels: documentation
